# Generated by Django 3.2.14 on 2022-08-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='downlad_count',
            new_name='download_count',
        ),
    ]
