# Generated by Django 3.2.14 on 2022-08-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
